app-db-backend = ""
halt-height = 0
halt-time = 0
iavl-cache-size = 781250
iavl-disable-fastnode = false
index-events = []
inter-block-cache = true
min-retain-blocks = 0
minimum-gas-prices = "0upokt"
pruning = "nothing"
pruning-interval = "0"
pruning-keep-recent = "0"
query-gas-limit = "0"

[api]
  address = "tcp://0.0.0.0:1317"
  enable = true
  enabled-unsafe-cors = true
  max-open-connections = 1000
  rpc-max-body-bytes = 1000000
  rpc-read-timeout = 10
  rpc-write-timeout = 0
  swagger = true

[grpc]
  address = "0.0.0.0:9090"
  enable = true
  max-recv-msg-size = "10485760"
  max-send-msg-size = "2147483647"

[grpc-web]
  enable = true

[mempool]
  max-txs = 10000

[poktroll]

  [poktroll.telemetry]
    cardinality-level = "high"

[rpc]
  cors_allowed_origins = ["*"]

[state-sync]
  snapshot-interval = 0
  snapshot-keep-recent = 2

[streaming]

  [streaming.abci]
    keys = []
    plugin = ""
    stop-node-on-err = true

[telemetry]
  datadog-hostname = ""
  enable-hostname = false
  enable-hostname-label = false
  enable-service-label = false
  enabled = true
  global-labels = []
  metrics-sink = "mem"
  prometheus-retention-time = 86400
  service-name = ""
  statsd-addr = ""
