# Pocket node URL that exposes CometBFT JSON-RPC API.
# This can be used by the Cosmos client SDK, event subscriptions, etc...
query_node_rpc_url: tcp://poktroll-validator:26657
# Pocket node URL that exposes the Cosmos gRPC service, dedicated to querying purposes.
query_node_grpc_url: tcp://poktroll-validator:9090
# The name of the key (in the keyring) that will be used to sign relays
signing_key: app1
# Whether the server should sign all incoming requests with its own ring (for applications)
self_signing: true
# The host and port that the appgate server will listen on
listening_endpoint: http://localhost:42069
# Prometheus exporter configuration
metrics:
  # Turn on/off the metrics exporter
  enabled: true
  # The address that the metrics exporter will listen on. Can be just a port, or host:port
  addr: :9090
pprof:
  enabled: true
  addr: localhost:6060
