config:
  smt_store_path: /root/.poktroll/smt
  metrics:
    enabled: true
    addr: :9090
  pocket_node:
    query_node_rpc_url: tcp://validator-poktroll-validator:26657
    query_node_grpc_url: tcp://validator-poktroll-validator:9090
    tx_node_rpc_url: tcp://validator-poktroll-validator:26657
  suppliers: []
  pprof:
    enabled: true
    addr: localhost:6060
  ping:
    enabled: true
    addr: localhost:8081
  forward:
    enabled: true
    addr: localhost:10000
    token: 8cc09793290cd64d8a9bc80eaae4fbeef5f7cf797b0c70e078d2a5b81d74f12c
