config:
  smt_store_path: smt_stores
  metrics:
    enabled: true
    addr: :9090
  pocket_node:
    query_node_rpc_url: tcp://validator-poktroll-validator:36657
    query_node_grpc_url: tcp://validator-poktroll-validator:36658
    tx_node_rpc_url: tcp://validator-poktroll-validator:36657
  proxies:
  - proxy_name: http-proxy
    type: http
    host: 0.0.0.0:8545
  suppliers: []
  pprof:
    enabled: true
    addr: localhost:6060
