fund_on_start: true

chain_id: agoriclocal

image:
  repository: agoric
  tag: latest
  pullPolicy: Never

mnemonic: "beach prize number regular tiger aware ring shiver path dizzy please bacon steel car crash youth rural history furnace possible property chicken entire system"

service:
  type: ClusterIP
  ports:
    p2p: 26656
    rpc: 26657
    rest: 1317
    grpc: 9090

env:
  DEST: "1"
  DEBUG: "SwingSet:ls,SwingSet:vat"

command:
  - /usr/src/upgrade-test-scripts/entrypoint.sh
